package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Attendees generated by hbm2java
 */
@Entity
@Table(name="attendees"
    ,schema="public"
)
public class Attendees  implements java.io.Serializable {


     private long id;
     private Events events;
     private String firstName;
     private String lastName;
     private String pronouns;
     private String badgeId;
     private Set<Plays> playses = new HashSet<Plays>(0);
     private Set<Checkouts> checkoutses = new HashSet<Checkouts>(0);

    public Attendees() {
    }

    public Attendees(long id, Events events, String firstName, String lastName, String pronouns, String badgeId, Set<Plays> playses, Set<Checkouts> checkoutses) {
       this.id = id;
       this.events = events;
       this.firstName = firstName;
       this.lastName = lastName;
       this.pronouns = pronouns;
       this.badgeId = badgeId;
       this.playses = playses;
       this.checkoutses = checkoutses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event", nullable=false)
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="pronouns", nullable=false)
    public String getPronouns() {
        return this.pronouns;
    }
    
    public void setPronouns(String pronouns) {
        this.pronouns = pronouns;
    }

    
    @Column(name="badge_id", nullable=false)
    public String getBadgeId() {
        return this.badgeId;
    }
    
    public void setBadgeId(String badgeId) {
        this.badgeId = badgeId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attendees")
    public Set<Plays> getPlayses() {
        return this.playses;
    }
    
    public void setPlayses(Set<Plays> playses) {
        this.playses = playses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attendees")
    public Set<Checkouts> getCheckoutses() {
        return this.checkoutses;
    }
    
    public void setCheckoutses(Set<Checkouts> checkoutses) {
        this.checkoutses = checkoutses;
    }




}


