package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Checkouts generated by hbm2java
 */
@Entity
@Table(name="checkouts"
    ,schema="public"
)
public class Checkouts  implements java.io.Serializable {


     private long id;
     private GameCopies gameCopies;
     private Attendees attendees;
     private OffsetDateTime startDatetime;
     private OffsetDateTime endDatetime;
     private Set<Plays> playses = new HashSet<Plays>(0);

    public Checkouts() {
    }

    public Checkouts(long id, GameCopies gameCopies, Attendees attendees, OffsetDateTime startDatetime, OffsetDateTime endDatetime, Set<Plays> playses) {
       this.id = id;
       this.gameCopies = gameCopies;
       this.attendees = attendees;
       this.startDatetime = startDatetime;
       this.endDatetime = endDatetime;
       this.playses = playses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="game_copy_id", nullable=false)
    public GameCopies getGameCopies() {
        return this.gameCopies;
    }
    
    public void setGameCopies(GameCopies gameCopies) {
        this.gameCopies = gameCopies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attendee_id", nullable=false)
    public Attendees getAttendees() {
        return this.attendees;
    }
    
    public void setAttendees(Attendees attendees) {
        this.attendees = attendees;
    }

    
    @Column(name="start_datetime", nullable=false, length=29)
    public OffsetDateTime getStartDatetime() {
        return this.startDatetime;
    }
    
    public void setStartDatetime(OffsetDateTime startDatetime) {
        this.startDatetime = startDatetime;
    }

    
    @Column(name="end_datetime", length=29)
    public OffsetDateTime getEndDatetime() {
        return this.endDatetime;
    }
    
    public void setEndDatetime(OffsetDateTime endDatetime) {
        this.endDatetime = endDatetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="checkouts")
    public Set<Plays> getPlayses() {
        return this.playses;
    }
    
    public void setPlayses(Set<Plays> playses) {
        this.playses = playses;
    }




}


