package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Checkout generated by hbm2java
 */
@Entity
@Table(name="checkouts"
    ,schema="public"
)
public class Checkout  implements java.io.Serializable {


     private Long id;
     private LibraryGameCopy libraryGameCopy;
     private Attendee attendee;
     private OffsetDateTime startDatetime;
     private OffsetDateTime endDatetime;
     private Set<Play> plays = new HashSet<Play>(0);

    public Checkout() {
    }

    public Checkout(LibraryGameCopy libraryGameCopy, Attendee attendee, OffsetDateTime startDatetime, OffsetDateTime endDatetime, Set<Play> plays) {
       this.libraryGameCopy = libraryGameCopy;
       this.attendee = attendee;
       this.startDatetime = startDatetime;
       this.endDatetime = endDatetime;
       this.plays = plays;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.CheckoutIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.CheckoutIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="library_game_copy_id", nullable=false)
    public LibraryGameCopy getLibraryGameCopy() {
        return this.libraryGameCopy;
    }
    
    public void setLibraryGameCopy(LibraryGameCopy libraryGameCopy) {
        this.libraryGameCopy = libraryGameCopy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attendee_id", nullable=false)
    public Attendee getAttendee() {
        return this.attendee;
    }
    
    public void setAttendee(Attendee attendee) {
        this.attendee = attendee;
    }

    
    @Column(name="start_datetime", nullable=false, length=29)
    public OffsetDateTime getStartDatetime() {
        return this.startDatetime;
    }
    
    public void setStartDatetime(OffsetDateTime startDatetime) {
        this.startDatetime = startDatetime;
    }

    
    @Column(name="end_datetime", length=29)
    public OffsetDateTime getEndDatetime() {
        return this.endDatetime;
    }
    
    public void setEndDatetime(OffsetDateTime endDatetime) {
        this.endDatetime = endDatetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="checkout")
    public Set<Play> getPlays() {
        return this.plays;
    }
    
    public void setPlays(Set<Play> plays) {
        this.plays = plays;
    }




}


