package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="events"
    ,schema="public"
)
public class Event  implements java.io.Serializable {


     private Long id;
     private String title;
     private OffsetDateTime startDatetime;
     private OffsetDateTime endDatetime;
     private Set<Attendee> attendees = new HashSet<Attendee>(0);
     private Set<Library> libraries = new HashSet<Library>(0);

    public Event() {
    }

    public Event(String title, OffsetDateTime startDatetime, OffsetDateTime endDatetime, Set<Attendee> attendees, Set<Library> libraries) {
       this.title = title;
       this.startDatetime = startDatetime;
       this.endDatetime = endDatetime;
       this.attendees = attendees;
       this.libraries = libraries;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.EventIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.EventIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="start_datetime", nullable=false, length=29)
    public OffsetDateTime getStartDatetime() {
        return this.startDatetime;
    }
    
    public void setStartDatetime(OffsetDateTime startDatetime) {
        this.startDatetime = startDatetime;
    }

    
    @Column(name="end_datetime", nullable=false, length=29)
    public OffsetDateTime getEndDatetime() {
        return this.endDatetime;
    }
    
    public void setEndDatetime(OffsetDateTime endDatetime) {
        this.endDatetime = endDatetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<Attendee> getAttendees() {
        return this.attendees;
    }
    
    public void setAttendees(Set<Attendee> attendees) {
        this.attendees = attendees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<Library> getLibraries() {
        return this.libraries;
    }
    
    public void setLibraries(Set<Library> libraries) {
        this.libraries = libraries;
    }




}


