package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name="events"
    ,schema="public"
)
public class Events  implements java.io.Serializable {


     private long id;
     private String title;
     private OffsetDateTime startDatetime;
     private OffsetDateTime endDatetime;
     private Set<Attendees> attendeeses = new HashSet<Attendees>(0);
     private Set<Libraries> librarieses = new HashSet<Libraries>(0);

    public Events() {
    }

    public Events(long id, String title, OffsetDateTime startDatetime, OffsetDateTime endDatetime, Set<Attendees> attendeeses, Set<Libraries> librarieses) {
       this.id = id;
       this.title = title;
       this.startDatetime = startDatetime;
       this.endDatetime = endDatetime;
       this.attendeeses = attendeeses;
       this.librarieses = librarieses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="start_datetime", nullable=false, length=29)
    public OffsetDateTime getStartDatetime() {
        return this.startDatetime;
    }
    
    public void setStartDatetime(OffsetDateTime startDatetime) {
        this.startDatetime = startDatetime;
    }

    
    @Column(name="end_datetime", nullable=false, length=29)
    public OffsetDateTime getEndDatetime() {
        return this.endDatetime;
    }
    
    public void setEndDatetime(OffsetDateTime endDatetime) {
        this.endDatetime = endDatetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="events")
    public Set<Attendees> getAttendeeses() {
        return this.attendeeses;
    }
    
    public void setAttendeeses(Set<Attendees> attendeeses) {
        this.attendeeses = attendeeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="events")
    public Set<Libraries> getLibrarieses() {
        return this.librarieses;
    }
    
    public void setLibrarieses(Set<Libraries> librarieses) {
        this.librarieses = librarieses;
    }




}


