package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Games generated by hbm2java
 */
@Entity
@Table(name="games"
    ,schema="public"
)
public class Games  implements java.io.Serializable {


     private long id;
     private String title;
     private Set<GameCopies> gameCopieses = new HashSet<GameCopies>(0);

    public Games() {
    }

    public Games(long id, String title, Set<GameCopies> gameCopieses) {
       this.id = id;
       this.title = title;
       this.gameCopieses = gameCopieses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="games")
    public Set<GameCopies> getGameCopieses() {
        return this.gameCopieses;
    }
    
    public void setGameCopieses(Set<GameCopies> gameCopieses) {
        this.gameCopieses = gameCopieses;
    }




}


