package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name="games"
    ,schema="public"
)
public class Game  implements java.io.Serializable {


     private Long id;
     private String title;
     private Set<GameCopy> gameCopies = new HashSet<GameCopy>(0);

    public Game() {
    }

    public Game(String title, Set<GameCopy> gameCopies) {
       this.title = title;
       this.gameCopies = gameCopies;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.GameIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.GameIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="game")
    public Set<GameCopy> getGameCopies() {
        return this.gameCopies;
    }
    
    public void setGameCopies(Set<GameCopy> gameCopies) {
        this.gameCopies = gameCopies;
    }




}


