package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * GameCopy generated by hbm2java
 */
@Entity
@Table(name="game_copies"
    ,schema="public"
)
public class GameCopy  implements java.io.Serializable {


     private Long id;
     private Game game;
     private String owner;
     private String notes;
     private Set<LibraryGameCopy> libraryGameCopies = new HashSet<LibraryGameCopy>(0);

    public GameCopy() {
    }

    public GameCopy(Game game, String owner, String notes, Set<LibraryGameCopy> libraryGameCopies) {
       this.game = game;
       this.owner = owner;
       this.notes = notes;
       this.libraryGameCopies = libraryGameCopies;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.GameCopyIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.GameCopyIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="game_id", nullable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }

    
    @Column(name="owner", nullable=false)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gameCopy")
    public Set<LibraryGameCopy> getLibraryGameCopies() {
        return this.libraryGameCopies;
    }
    
    public void setLibraryGameCopies(Set<LibraryGameCopy> libraryGameCopies) {
        this.libraryGameCopies = libraryGameCopies;
    }




}


