package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Library generated by hbm2java
 */
@Entity
@Table(name="libraries"
    ,schema="public"
)
public class Library  implements java.io.Serializable {


     private Long id;
     private Event event;
     private String name;
     private Set<LibraryGameCopy> libraryGameCopies = new HashSet<LibraryGameCopy>(0);

    public Library() {
    }

    public Library(Event event, String name, Set<LibraryGameCopy> libraryGameCopies) {
       this.event = event;
       this.name = name;
       this.libraryGameCopies = libraryGameCopies;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.LibraryIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.LibraryIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="library")
    public Set<LibraryGameCopy> getLibraryGameCopies() {
        return this.libraryGameCopies;
    }
    
    public void setLibraryGameCopies(Set<LibraryGameCopy> libraryGameCopies) {
        this.libraryGameCopies = libraryGameCopies;
    }




}


