package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * LibrariesGameCopies generated by hbm2java
 */
@Entity
@Table(name="libraries_game_copies"
    ,schema="public"
)
public class LibrariesGameCopies  implements java.io.Serializable {


     private long id;
     private GameCopies gameCopies;
     private Libraries libraries;
     private String libraryCopyId;

    public LibrariesGameCopies() {
    }

    public LibrariesGameCopies(long id, GameCopies gameCopies, Libraries libraries, String libraryCopyId) {
       this.id = id;
       this.gameCopies = gameCopies;
       this.libraries = libraries;
       this.libraryCopyId = libraryCopyId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="game_copy_id", nullable=false)
    public GameCopies getGameCopies() {
        return this.gameCopies;
    }
    
    public void setGameCopies(GameCopies gameCopies) {
        this.gameCopies = gameCopies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="library_id", nullable=false)
    public Libraries getLibraries() {
        return this.libraries;
    }
    
    public void setLibraries(Libraries libraries) {
        this.libraries = libraries;
    }

    
    @Column(name="library_copy_id", nullable=false)
    public String getLibraryCopyId() {
        return this.libraryCopyId;
    }
    
    public void setLibraryCopyId(String libraryCopyId) {
        this.libraryCopyId = libraryCopyId;
    }




}


