package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * LibraryGameCopy generated by hbm2java
 */
@Entity
@Table(name="library_game_copies"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"library_copy_id", "library_id"}) 
)
public class LibraryGameCopy  implements java.io.Serializable {


     private Long id;
     private GameCopy gameCopy;
     private Library library;
     private String libraryCopyId;
     private Set<Checkout> checkouts = new HashSet<Checkout>(0);

    public LibraryGameCopy() {
    }

    public LibraryGameCopy(GameCopy gameCopy, Library library, String libraryCopyId, Set<Checkout> checkouts) {
       this.gameCopy = gameCopy;
       this.library = library;
       this.libraryCopyId = libraryCopyId;
       this.checkouts = checkouts;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.LibraryGameCopyIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.LibraryGameCopyIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="game_copy_id", nullable=false)
    public GameCopy getGameCopy() {
        return this.gameCopy;
    }
    
    public void setGameCopy(GameCopy gameCopy) {
        this.gameCopy = gameCopy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="library_id", nullable=false)
    public Library getLibrary() {
        return this.library;
    }
    
    public void setLibrary(Library library) {
        this.library = library;
    }

    
    @Column(name="library_copy_id", nullable=false)
    public String getLibraryCopyId() {
        return this.libraryCopyId;
    }
    
    public void setLibraryCopyId(String libraryCopyId) {
        this.libraryCopyId = libraryCopyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libraryGameCopy")
    public Set<Checkout> getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set<Checkout> checkouts) {
        this.checkouts = checkouts;
    }




}


