package com.geekway.conlibrary.db.entity;
// Generated Jul 13, 2023, 12:10:19 AM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Play generated by hbm2java
 */
@Entity
@Table(name="plays"
    ,schema="public"
)
public class Play  implements java.io.Serializable {


     private Long id;
     private Checkout checkout;
     private Attendee attendee;
     private Short rating;

    public Play() {
    }

    public Play(Checkout checkout, Attendee attendee, Short rating) {
       this.checkout = checkout;
       this.attendee = attendee;
       this.rating = rating;
    }
   
     @GenericGenerator(name="com.geekway.conlibrary.db.entity.PlayIdGenerator", strategy="org.hibernate.id.IdentityGenerator")@Id @GeneratedValue(generator="com.geekway.conlibrary.db.entity.PlayIdGenerator")

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="checkout_id", nullable=false)
    public Checkout getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Checkout checkout) {
        this.checkout = checkout;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attendee_id", nullable=false)
    public Attendee getAttendee() {
        return this.attendee;
    }
    
    public void setAttendee(Attendee attendee) {
        this.attendee = attendee;
    }

    
    @Column(name="rating")
    public Short getRating() {
        return this.rating;
    }
    
    public void setRating(Short rating) {
        this.rating = rating;
    }




}


