package com.geekway.conlibrary.db.entity;
// Generated Jul 8, 2023, 4:17:37 PM by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Plays generated by hbm2java
 */
@Entity
@Table(name="plays"
    ,schema="public"
)
public class Plays  implements java.io.Serializable {


     private long id;
     private Checkouts checkouts;
     private Attendees attendees;
     private Short rating;

    public Plays() {
    }

    public Plays(long id, Checkouts checkouts, Attendees attendees, Short rating) {
       this.id = id;
       this.checkouts = checkouts;
       this.attendees = attendees;
       this.rating = rating;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="checkout_id", nullable=false)
    public Checkouts getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Checkouts checkouts) {
        this.checkouts = checkouts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attendee_id", nullable=false)
    public Attendees getAttendees() {
        return this.attendees;
    }
    
    public void setAttendees(Attendees attendees) {
        this.attendees = attendees;
    }

    
    @Column(name="rating")
    public Short getRating() {
        return this.rating;
    }
    
    public void setRating(Short rating) {
        this.rating = rating;
    }




}


